// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package data

import ()

type Employees struct {
	EmployeeID int32  `json:"employee_id"`
	FirstName  string `json:"first_name" validate:"required,alpha"`
	LastName   string `json:"last_name" validate:"required,alpha"`
	Email      string `json:"email" validate:"required,email"`
	IpAddress  string `json:"ip_address" validate:"required,ipv4"`
}
